#!/bin/bash
# Post-install shell configuration and reports

SHELL_PROFILE_MODE="starship"
LINK_MODE="symlink"
INSTALL_REPORT_OK=()
INSTALL_REPORT_SKIP=()
INSTALL_REPORT_FAIL=()
INSTALL_REPORT_CONFIG=()

report_ok() { INSTALL_REPORT_OK+=("$1"); }
report_skip() { INSTALL_REPORT_SKIP+=("$1"); }
report_fail() { INSTALL_REPORT_FAIL+=("$1"); }
report_config() { INSTALL_REPORT_CONFIG+=("$1"); }

# Resolve DOTFILES_DIR for shell configs (may live outside ~/dotfiles)
resolve_dotfiles_dir() {
    if [[ -n "${DOTFILES_DIR:-}" && -d "$DOTFILES_DIR" ]]; then
        echo "$DOTFILES_DIR"
        return
    fi
    if [[ -d "$HOME/dotfiles" ]]; then
        echo "$HOME/dotfiles"
        return
    fi
    if [[ -L "$HOME/.zshrc" ]]; then
        local target
        target="$(readlink "$HOME/.zshrc")"
        echo "$(cd "$(dirname "$target")" 2>/dev/null && pwd)"
        return
    fi
    echo "$HOME/dotfiles"
}

# Write features file consumed by .zshrc
write_shell_features() {
    local features_file="$STATE_DIR/shell-features.zsh"
    local df
    df="$(resolve_dotfiles_dir)"

    local enable_starship=0
    [[ " ${SELECTED_IDS[*]} " == *" starship "* || "$SHELL_PROFILE_MODE" == "starship" ]] && enable_starship=1

    if dry_run_is_active; then
        dry_run_add_step "Write shell features" \
            "write $features_file (starship=$enable_starship)" \
            "$features_file" "sourced by ~/.zshrc" "false" ""
        return 0
    fi

    state_init
    cat > "$features_file" <<EOF
# Generated by setup — do not edit by hand (re-run setup to change)
export DOTFILES_DIR="${df}"
export STARSHIP_CONFIG="\${STARSHIP_CONFIG:-\${DOTFILES_DIR}/.config/starship.toml}"
export DOTFILES_ENABLE_STARSHIP=${enable_starship}
export DOTFILES_ENABLE_OMZ=0
export DOTFILES_SHELL_PROFILE="${SHELL_PROFILE_MODE:-starship}"
EOF

    state_log_install "shell-features" "Shell features file" "config" \
        "write $features_file" "$features_file" "" "" "" ""
    report_config "Shell profile → ${SHELL_PROFILE_MODE:-starship} (starship=$enable_starship)"
    prompt_success "Wrote shell features: $features_file"
}

configure_starship() {
    [[ " ${SELECTED_IDS[*]} " != *" starship "* ]] && return 0

    if dry_run_is_active; then
        dry_run_add_step "Configure Starship" \
            "STARSHIP_CONFIG → \$DOTFILES_DIR/.config/starship.toml + shell init via features" \
            "$(resolve_dotfiles_dir)/.config/starship.toml" "" "false" ""
        return 0
    fi

    report_config "Starship config → $(resolve_dotfiles_dir)/.config/starship.toml"
}

# Install path into home (symlink or copy)
install_dotfile_path() {
    local rel="$1"
    local source="$DOTFILES_DIR/$rel"
    local target="$HOME/$rel"

    if [[ ! -e "$source" ]]; then
        prompt_warn "Missing in repo: $rel — skipping"
        report_skip "dotfile $rel (missing)"
        return 0
    fi

    if [[ "$LINK_MODE" == "copy" ]]; then
        local cmd="cp -a \"$source\" \"$target\""
        if dry_run_is_active; then
            dry_run_add_step "Copy $rel" "$cmd" "$target" "backup existing if present" "false" ""
            return 0
        fi
        mkdir -p "$(dirname "$target")"
        local backup=""
        if [[ -e "$target" || -L "$target" ]]; then
            backup="$(state_backup_path "$target")"
        fi
        if [[ -d "$source" && ! -L "$source" ]]; then
            rm -rf "$target"
            cp -a "$source" "$target"
        else
            cp -a "$source" "$target"
        fi
        state_log_install "copy-${rel//\//-}" "Copy $rel" "symlink" "$cmd" \
            "$target" "copy" "$source" "$target" "$backup"
        prompt_success "Copied $rel"
        report_ok "copy $rel"
    else
        symlink_dotfile_safe "$rel"
        report_ok "symlink $rel"
    fi
}

# Offer ~/.zprofile on the user's machine for local secrets (API keys, tokens)
offer_secrets_zprofile() {
    local secrets_file="$HOME/.zprofile"
    local marker_start="# >>> dotfiles-secrets >>>"
    local marker_end="# <<< dotfiles-secrets <<<"

    if [[ -f "$secrets_file" ]] && grep -qF "$marker_start" "$secrets_file" 2>/dev/null; then
        prompt_info "Secrets section already present in $secrets_file."
        report_config "Secrets section already in ~/.zprofile" 2>/dev/null || true
        return 0
    fi

    prompt_style "── Local secrets ──"
    prompt_info "Keep API keys and tokens in ~/.zprofile on this machine (outside the repo)."
    if [[ -f "$secrets_file" ]]; then
        if ! prompt_confirm "Add a secrets section to ~/.zprofile?" "true"; then
            prompt_warn "Skipping secrets .zprofile."
            report_skip "secrets ~/.zprofile" 2>/dev/null || true
            return 0
        fi
    else
        if ! prompt_confirm "Create ~/.zprofile for secrets?" "true"; then
            prompt_warn "Skipping secrets .zprofile."
            report_skip "secrets ~/.zprofile" 2>/dev/null || true
            return 0
        fi
    fi

    # Dry-run: record only — never create or modify ~/.zprofile
    if dry_run_is_active 2>/dev/null; then
        if [[ -f "$secrets_file" ]]; then
            dry_run_add_step "Add secrets section to ~/.zprofile" \
                "append $marker_start … $marker_end block for API keys / tokens" \
                "$secrets_file" "lives on the machine, outside the repo" "false" ""
        else
            dry_run_add_step "Create ~/.zprofile for secrets" \
                "write $secrets_file with secrets template for API keys / tokens" \
                "$secrets_file" "lives on the machine, outside the repo" "false" ""
        fi
        return 0
    fi

    {
        echo ""
        echo "$marker_start"
        echo "# Local secrets — lives in \$HOME (not in the dotfiles repo)"
        echo "# Examples:"
        echo "# export OPENAI_API_KEY=\"…\""
        echo "# export ANTHROPIC_API_KEY=\"…\""
        echo "# export GH_TOKEN=\"…\""
        echo "$marker_end"
    } >> "$secrets_file"

    state_log_install "secrets-zprofile" "Secrets ~/.zprofile" "config" \
        "append secrets block to $secrets_file" "$secrets_file" \
        "$secrets_file" "" "" ""
    prompt_success "Secrets ready in $secrets_file."
    prompt_info "Add your exports inside the marked block, then restart your terminal."
    report_config "Secrets section in ~/.zprofile" 2>/dev/null || true
}

print_final_report() {
    echo ""
    prompt_style "── Setup report ──"
    if [[ ${#INSTALL_REPORT_OK[@]} -gt 0 ]]; then
        prompt_success "Installed / linked (${#INSTALL_REPORT_OK[@]}):"
        local i
        for i in "${INSTALL_REPORT_OK[@]}"; do echo "  ✓ $i"; done
    fi
    if [[ ${#INSTALL_REPORT_SKIP[@]} -gt 0 ]]; then
        prompt_warn "Skipped (${#INSTALL_REPORT_SKIP[@]}):"
        local i
        for i in "${INSTALL_REPORT_SKIP[@]}"; do echo "  • $i"; done
    fi
    if [[ ${#INSTALL_REPORT_FAIL[@]} -gt 0 ]]; then
        prompt_error "Failed (${#INSTALL_REPORT_FAIL[@]}):"
        local i
        for i in "${INSTALL_REPORT_FAIL[@]}"; do echo "  ✗ $i"; done
    fi
    if [[ ${#INSTALL_REPORT_CONFIG[@]} -gt 0 ]]; then
        prompt_info "Configured:"
        local i
        for i in "${INSTALL_REPORT_CONFIG[@]}"; do echo "  → $i"; done
    fi

    echo ""
    prompt_info "Next steps:"
    echo "  1. Restart your terminal (or run: exec \$SHELL)"
    if [[ " ${SELECTED_IDS[*]} " == *" starship "* ]] || [[ " ${SELECTED_IDS[*]} " == *"_nerd "* ]]; then
        echo "  2. Set your terminal font to a Nerd Font (e.g. SFMono Nerd Font)"
    fi
    echo "  3. Review: $STATE_DIR/shell-features.zsh"
    if [[ -f "$HOME/.zprofile" ]] && grep -qF "# >>> dotfiles-secrets >>>" "$HOME/.zprofile" 2>/dev/null; then
        echo "  4. Add secrets to ~/.zprofile (outside the repo)"
        echo "  5. Undo later: ./setup.sh --undo"
    else
        echo "  4. Undo later: ./setup.sh --undo"
    fi
    echo ""
}
