#!/bin/bash
# Post-install shell configuration, conflict handling, reports

SHELL_PROFILE_MODE="" # starship | oh-my-zsh | merged
LINK_MODE="symlink"   # symlink | copy
INSTALL_REPORT_OK=()
INSTALL_REPORT_SKIP=()
INSTALL_REPORT_FAIL=()
INSTALL_REPORT_CONFIG=()

report_ok() { INSTALL_REPORT_OK+=("$1"); }
report_skip() { INSTALL_REPORT_SKIP+=("$1"); }
report_fail() { INSTALL_REPORT_FAIL+=("$1"); }
report_config() { INSTALL_REPORT_CONFIG+=("$1"); }

# Resolve DOTFILES_DIR for shell configs (may live outside ~/dotfiles)
resolve_dotfiles_dir() {
    if [[ -n "${DOTFILES_DIR:-}" && -d "$DOTFILES_DIR" ]]; then
        echo "$DOTFILES_DIR"
        return
    fi
    if [[ -d "$HOME/dotfiles" ]]; then
        echo "$HOME/dotfiles"
        return
    fi
    # If .zshrc is a symlink into a repo, use that
    if [[ -L "$HOME/.zshrc" ]]; then
        local target
        target="$(readlink "$HOME/.zshrc")"
        echo "$(cd "$(dirname "$target")/.." 2>/dev/null && pwd)"
        return
    fi
    echo "$HOME/dotfiles"
}

# Write features file consumed by .zshrc
write_shell_features() {
    local features_file="$STATE_DIR/shell-features.zsh"
    local df
    df="$(resolve_dotfiles_dir)"

    local enable_starship=0 enable_omz=0
    case "$SHELL_PROFILE_MODE" in
        starship) enable_starship=1; enable_omz=0 ;;
        oh-my-zsh) enable_starship=0; enable_omz=1 ;;
        merged) enable_starship=1; enable_omz=1 ;;
        *)
            [[ " ${SELECTED_IDS[*]} " == *" starship "* ]] && enable_starship=1
            [[ " ${SELECTED_IDS[*]} " == *" oh_my_zsh "* ]] && enable_omz=1
            if [[ $enable_starship -eq 1 && $enable_omz -eq 1 ]]; then
                enable_omz=0 # prefer starship unless user chose merged
            fi
            ;;
    esac

    if dry_run_is_active; then
        dry_run_add_step "Write shell features" \
            "write $features_file (starship=$enable_starship omz=$enable_omz)" \
            "$features_file" "sourced by ~/.zshrc" "false" ""
        return 0
    fi

    state_init
    cat > "$features_file" <<EOF
# Generated by setup wizard — do not edit by hand (re-run setup to change)
export DOTFILES_DIR="${df}"
export STARSHIP_CONFIG="\${STARSHIP_CONFIG:-\${DOTFILES_DIR}/.config/starship.toml}"
export DOTFILES_ENABLE_STARSHIP=${enable_starship}
export DOTFILES_ENABLE_OMZ=${enable_omz}
export DOTFILES_SHELL_PROFILE="${SHELL_PROFILE_MODE:-starship}"
EOF

    state_log_install "shell-features" "Shell features file" "config" \
        "write $features_file" "$features_file" "" "" "" ""
    report_config "Shell profile → ${SHELL_PROFILE_MODE:-auto} (starship=$enable_starship, omz=$enable_omz)"
    prompt_success "Wrote shell features: $features_file"
}

# Resolve Starship vs Oh My Zsh conflict
resolve_shell_profile_conflict() {
    local has_starship=false has_omz=false
    [[ " ${SELECTED_IDS[*]} " == *" starship "* ]] && has_starship=true
    [[ " ${SELECTED_IDS[*]} " == *" oh_my_zsh "* ]] && has_omz=true

    if [[ "$has_starship" != "true" || "$has_omz" != "true" ]]; then
        # Keep plan-provided mode only if it still makes sense
        if [[ -n "${SHELL_PROFILE_MODE:-}" ]]; then
            return 0
        fi
        if [[ "$has_omz" == "true" ]]; then
            SHELL_PROFILE_MODE="oh-my-zsh"
        elif [[ "$has_starship" == "true" ]]; then
            SHELL_PROFILE_MODE="starship"
        else
            SHELL_PROFILE_MODE=""
        fi
        return 0
    fi

    # Both selected — honor explicit mode from --plan / prefs
    if [[ -n "${SHELL_PROFILE_MODE:-}" ]]; then
        prompt_info "Using shell profile mode from plan/prefs: $SHELL_PROFILE_MODE"
        return 0
    fi

    prompt_style "── Shell profile conflict ──"
    prompt_warn "You selected both Starship and Oh My Zsh."
    prompt_info "This repo's .zshrc can load one primary profile (or a merged mode)."

    if [[ -n "${YES_MODE:-}" ]]; then
        SHELL_PROFILE_MODE="merged"
        prompt_info "Using profile mode: $SHELL_PROFILE_MODE (-y default)"
        return 0
    fi

    local choice
    choice="$(prompt_choose_one "How should your zsh profile work?" \
        "Starship + this repo's .zshrc (recommended; OMZ installed but not loaded)" \
        "Oh My Zsh as primary (stock OMZ theme/plugins)" \
        "Merged (load OMZ plugins, use Starship as prompt)")"

    case "$choice" in
        Oh\ My\ Zsh*) SHELL_PROFILE_MODE="oh-my-zsh" ;;
        Merged*) SHELL_PROFILE_MODE="merged" ;;
        *) SHELL_PROFILE_MODE="starship" ;;
    esac
}

# After OMZ install, optionally patch ~/.zshrc if using omz/merged without our symlink
configure_oh_my_zsh_profile() {
    [[ "$SHELL_PROFILE_MODE" != "oh-my-zsh" && "$SHELL_PROFILE_MODE" != "merged" ]] && return 0
    [[ ! -d "$HOME/.oh-my-zsh" ]] && return 0

    if dry_run_is_active; then
        dry_run_add_step "Configure Oh My Zsh" \
            "ensure OMZ loads; merged adds starship init" \
            "$HOME/.zshrc" "" "false" ""
        return 0
    fi

    # If user symlinked our .zshrc, features file handles OMZ — nothing else needed
    if [[ -L "$HOME/.zshrc" ]]; then
        local current
        current="$(readlink "$HOME/.zshrc" 2>/dev/null || true)"
        if [[ "$current" == "$DOTFILES_DIR/.zshrc" ]]; then
            report_config "Oh My Zsh will load via modular .zshrc (mode=$SHELL_PROFILE_MODE)"
            return 0
        fi
    fi

    # Stock OMZ .zshrc: append starship for merged mode
    if [[ "$SHELL_PROFILE_MODE" == "merged" && -f "$HOME/.zshrc" ]]; then
        if ! grep -q "starship init zsh" "$HOME/.zshrc" 2>/dev/null; then
            {
                echo ""
                echo "# >>> dotfiles-setup >>>"
                echo "command -v starship >/dev/null && eval \"\$(starship init zsh)\""
                echo "# <<< dotfiles-setup <<<"
            } >> "$HOME/.zshrc"
            report_config "Appended Starship init to existing ~/.zshrc (merged mode)"
        fi
    fi
}

configure_starship() {
    [[ " ${SELECTED_IDS[*]} " != *" starship "* ]] && return 0

    if dry_run_is_active; then
        dry_run_add_step "Configure Starship" \
            "STARSHIP_CONFIG → \$DOTFILES_DIR/.config/starship.toml + shell init via features" \
            "$(resolve_dotfiles_dir)/.config/starship.toml" "" "false" ""
        return 0
    fi

    report_config "Starship config → $(resolve_dotfiles_dir)/.config/starship.toml"
}

# Smart default symlink list based on selections
smart_symlink_defaults() {
    local options=()
    # Always useful when using this repo
    options+=(".zshrc")
    options+=(".zshenv")
    options+=(".config/starship.toml")

    [[ " ${SELECTED_IDS[*]} " == *" starship "* || "$SHELL_PROFILE_MODE" == "starship" || "$SHELL_PROFILE_MODE" == "merged" ]] && \
        options+=(".config/starship.toml")

    # Prefer full .config if many config pieces, else granular
    if [[ " ${SELECTED_IDS[*]} " == *" zed "* ]] || [[ " ${SELECTED_IDS[*]} " == *" fish "* ]]; then
        options+=(".config")
    fi

    [[ " ${SELECTED_IDS[*]} " == *" warp "* ]] && options+=(".warp")
    [[ " ${SELECTED_IDS[*]} " == *" zed "* ]] && options+=(".config/zed")
    [[ " ${SELECTED_IDS[*]} " == *" fish "* || "${SELECTED_SHELL:-}" == "fish" ]] && options+=(".config/fish")

    # Dedupe
    local seen=" "
    local out=()
    local o
    for o in "${options[@]}"; do
        if [[ "$seen" != *" $o "* ]]; then
            out+=("$o")
            seen="$seen$o "
        fi
    done
    printf '%s\n' "${out[@]}"
}

choose_link_mode() {
    if [[ -n "${YES_MODE:-}" ]]; then
        LINK_MODE="${LINK_MODE:-symlink}"
        return 0
    fi
    local choice
    choice="$(prompt_choose_one "How should dotfiles be linked into \$HOME?" \
        "Symlink (recommended — edits track the repo)" \
        "Copy (standalone copies into \$HOME)")"
    case "$choice" in
        Copy*) LINK_MODE="copy" ;;
        *) LINK_MODE="symlink" ;;
    esac
}

# Install path into home (symlink or copy)
install_dotfile_path() {
    local rel="$1"
    local source="$DOTFILES_DIR/$rel"
    local target="$HOME/$rel"

    if [[ ! -e "$source" ]]; then
        prompt_warn "Missing in repo: $rel — skipping"
        report_skip "dotfile $rel (missing)"
        return 0
    fi

    mkdir -p "$(dirname "$target")"

    if [[ "$LINK_MODE" == "copy" ]]; then
        local cmd="cp -a \"$source\" \"$target\""
        if dry_run_is_active; then
            dry_run_add_step "Copy $rel" "$cmd" "$target" "backup existing if present" "false" ""
            return 0
        fi
        local backup=""
        if [[ -e "$target" || -L "$target" ]]; then
            backup="$(state_backup_path "$target")"
        fi
        if [[ -d "$source" && ! -L "$source" ]]; then
            rm -rf "$target"
            cp -a "$source" "$target"
        else
            cp -a "$source" "$target"
        fi
        state_log_install "copy-${rel//\//-}" "Copy $rel" "symlink" "$cmd" \
            "$target" "copy" "$source" "$target" "$backup"
        prompt_success "Copied $rel"
        report_ok "copy $rel"
    else
        symlink_dotfile_safe "$rel"
        report_ok "symlink $rel"
    fi
}

print_final_report() {
    echo ""
    prompt_style "── Setup report ──"
    if [[ ${#INSTALL_REPORT_OK[@]} -gt 0 ]]; then
        prompt_success "Installed / linked (${#INSTALL_REPORT_OK[@]}):"
        local i
        for i in "${INSTALL_REPORT_OK[@]}"; do echo "  ✓ $i"; done
    fi
    if [[ ${#INSTALL_REPORT_SKIP[@]} -gt 0 ]]; then
        prompt_warn "Skipped (${#INSTALL_REPORT_SKIP[@]}):"
        local i
        for i in "${INSTALL_REPORT_SKIP[@]}"; do echo "  • $i"; done
    fi
    if [[ ${#INSTALL_REPORT_FAIL[@]} -gt 0 ]]; then
        prompt_error "Failed (${#INSTALL_REPORT_FAIL[@]}):"
        local i
        for i in "${INSTALL_REPORT_FAIL[@]}"; do echo "  ✗ $i"; done
    fi
    if [[ ${#INSTALL_REPORT_CONFIG[@]} -gt 0 ]]; then
        prompt_info "Configured:"
        local i
        for i in "${INSTALL_REPORT_CONFIG[@]}"; do echo "  → $i"; done
    fi

    echo ""
    prompt_info "Next steps:"
    echo "  1. Restart your terminal (or run: exec \$SHELL)"
    if [[ " ${SELECTED_IDS[*]} " == *" starship "* ]] || [[ " ${SELECTED_IDS[*]} " == *"_nerd "* ]]; then
        echo "  2. Set your terminal font to a Nerd Font (e.g. SFMono Nerd Font)"
    fi
    echo "  3. Review: $STATE_DIR/shell-features.zsh"
    echo "  4. Undo later: ./setup.sh --undo"
    echo ""
}

# Export current selection as a reusable plan file
export_plan_file() {
    local out="${1:-$STATE_DIR/last-plan.env}"
    state_init
    {
        echo "# Generated by setup wizard"
        echo "PKG_MGR=${PKG_MGR:-}"
        echo "PRESET_NAME=${PRESET_NAME:-custom}"
        echo "SHELL_PROFILE_MODE=${SHELL_PROFILE_MODE:-}"
        echo "LINK_MODE=${LINK_MODE:-symlink}"
        echo "SELECTED_SHELL=${SELECTED_SHELL:-}"
        echo "SELECTION_IDS=\"${SELECTED_IDS[*]}\""
        echo "SYMLINK_TARGETS=\"${SYMLINK_TARGETS[*]:-}\""
        echo "DOTFILES_DIR=${DOTFILES_DIR:-}"
    } > "$out"
    prompt_info "Saved plan: $out"
}

load_plan_file() {
    local file="$1"
    if [[ ! -f "$file" ]]; then
        prompt_error "Plan file not found: $file"
        return 1
    fi

    PKG_MGR="$(grep '^PKG_MGR=' "$file" | head -1 | cut -d= -f2-)"
    PRESET_NAME="$(grep '^PRESET_NAME=' "$file" | head -1 | cut -d= -f2-)"
    SHELL_PROFILE_MODE="$(grep '^SHELL_PROFILE_MODE=' "$file" | head -1 | cut -d= -f2-)"
    LINK_MODE="$(grep '^LINK_MODE=' "$file" | head -1 | cut -d= -f2-)"
    SELECTED_SHELL="$(grep '^SELECTED_SHELL=' "$file" | head -1 | cut -d= -f2-)"
    local selection_str targets_str df
    selection_str="$(grep '^SELECTION_IDS=' "$file" | head -1 | sed 's/^SELECTION_IDS="//;s/"$//')"
    targets_str="$(grep '^SYMLINK_TARGETS=' "$file" | head -1 | sed 's/^SYMLINK_TARGETS="//;s/"$//')"
    df="$(grep '^DOTFILES_DIR=' "$file" | head -1 | cut -d= -f2-)"
    [[ -n "$df" ]] && DOTFILES_DIR="$df"

    installer_clear_selections
    local id
    for id in $selection_str; do
        installer_add_selection "$id"
    done
    SYMLINK_TARGETS=()
    local p
    for p in $targets_str; do
        SYMLINK_TARGETS+=("$p")
    done
    PRESET_NAME="${PRESET_NAME:-custom}"
    prompt_success "Loaded plan from $file (${#SELECTED_IDS[@]} items)"
}
