#!/bin/bash
# Detect and apply migrations from older setups / unmanaged configs

MIGRATE_NEEDED=""
MIGRATE_REASONS=()
MIGRATE_ACTION=""  # none | upgrade | adopt | skip

migrate_detect() {
    MIGRATE_NEEDED=""
    MIGRATE_REASONS=()

    local state="${STATE_DIR:-$HOME/.dotfiles-setup}"
    if [[ -f "$state/install-log.jsonl" ]] || [[ -f "$state/setup.conf" ]]; then
        # Schema v1 / prior runs
        if [[ ! -f "$state/shell-features.zsh" ]] \
            || ! grep -q 'DOTFILES_SETUP_SCHEMA=2' "$state/shell-features.zsh" 2>/dev/null; then
            MIGRATE_REASONS+=("prior_setup")
        fi
    fi

    # Symlink pointing into a clone (old model)
    if [[ -L "$HOME/.zshrc" ]]; then
        local target
        target="$(readlink "$HOME/.zshrc" 2>/dev/null || true)"
        if [[ "$target" == *"/dotfiles/"* ]] || [[ "$target" == *"/dotfiles.zshrc" ]]; then
            MIGRATE_REASONS+=("old_symlink")
        elif [[ -n "$DOTFILES_DIR" && "$target" == "$DOTFILES_DIR"* ]]; then
            MIGRATE_REASONS+=("old_symlink")
        fi
    fi

    # Unmanaged zshrc (exists, not generated marker, not our symlink already flagged)
    if [[ -f "$HOME/.zshrc" && ! -L "$HOME/.zshrc" ]]; then
        if ! grep -q 'Generated by dotfiles-setup' "$HOME/.zshrc" 2>/dev/null; then
            MIGRATE_REASONS+=("unmanaged_zshrc")
        fi
    fi

    if [[ ${#MIGRATE_REASONS[@]} -gt 0 ]]; then
        MIGRATE_NEEDED=1
    fi
}

migrate_reasons_csv() {
    local IFS=,
    echo "${MIGRATE_REASONS[*]}"
}

# Interactive / yes-mode choice
pick_migrate() {
    migrate_detect
    MIGRATE_ACTION="none"
    [[ -n "$MIGRATE_NEEDED" ]] || return 0

    if [[ -n "${SETUP_MIGRATE:-}" ]]; then
        MIGRATE_ACTION="$SETUP_MIGRATE"
        return 0
    fi

    if [[ -n "${YES_MODE:-}" ]]; then
        MIGRATE_ACTION="upgrade"
        return 0
    fi

    local labels=(
        "Upgrade / regenerate managed configs  [default]"
        "Backup existing files and adopt generated setup"
        "Skip migration for now"
    )
    echo ""
    prompt_style "Existing configuration detected"
    local r
    for r in "${MIGRATE_REASONS[@]}"; do
        prompt_info "Signal: $r"
    done
    local pick
    pick="$(prompt_choose_one "Migration" "${labels[@]}")"
    case "$pick" in
        Backup*) MIGRATE_ACTION="adopt" ;;
        Skip*) MIGRATE_ACTION="skip" ;;
        *) MIGRATE_ACTION="upgrade" ;;
    esac
}

# Apply migration side-effects before generate (backup unmanaged files)
migrate_apply() {
    case "${MIGRATE_ACTION:-none}" in
        none|skip) return 0 ;;
        upgrade|adopt)
            if [[ " ${MIGRATE_REASONS[*]} " == *" unmanaged_zshrc "* ]] \
                || [[ " ${MIGRATE_REASONS[*]} " == *" old_symlink "* ]]; then
                if dry_run_is_active 2>/dev/null; then
                    dry_run_add_step "Migrate backup ~/.zshrc" "backup ~/.zshrc" "$HOME/.zshrc" "" "false" ""
                else
                    if [[ -e "$HOME/.zshrc" ]]; then
                        state_backup_path "$HOME/.zshrc" >/dev/null || true
                    fi
                    if [[ -L "$HOME/.zshrc" ]]; then
                        rm -f "$HOME/.zshrc"
                    fi
                fi
            fi
            if [[ -L "$HOME/.zshenv" ]]; then
                if dry_run_is_active 2>/dev/null; then
                    dry_run_add_step "Migrate unlink ~/.zshenv" "rm symlink" "$HOME/.zshenv" "" "false" ""
                else
                    state_backup_path "$HOME/.zshenv" >/dev/null || true
                    rm -f "$HOME/.zshenv"
                fi
            fi
            ;;
    esac
}
